### ISSUE TITLE
PR4424 - Error on outgoing transfers

### ISSUE THREAD

**Issue by hluaces** [hluaces/virtualname-whmcs#1]
The outgoing transfer cron job fails on some instances with the following error:

> [WHMCS Application] ERROR: Error: Call to undefined method WHMCS\Application::load_class() in /www/whmcs/public/modules/registrars/virtualname/lib/classes/class.domains.php:1638 Stack trace: #0 /www/whmcs/public/modules/registrars/virtualname/lib/classes/class.domains.php(767): Virtualname_domains->send_domains_notification('Full Administra...', 'WHMCS-Virtualna...', '<p>Listado de d...') #1 /www/whmcs/public/modules/registrars/virtualname/lib/crons/sync.php(89): Virtualname_domains->outbounds_mailing() #2 {main} {"exception":"[object] (Error(code: 0): Call to undefined method WHMCS\\Application::load_class() at /www/whmcs/public/modules/registrars/virtualname/lib/classes/class.domains.php:1638)"} []

This causes some domains to be stuck on the "Transfered away" status, which sends the customers constant emails about the transfer. This ceases when the domain is manually set to a "Cancelled" status.

The issue seems to be related to the way that the file `lib/classes/class.domains.php` is loading the `PHPMailer` class.

AFAIK it is not fixed on the original repo so I made a branch on this repo to address the issue until it's fixed upstream:

https://github.com/hluaces/virtualname-whmcs/compare/fix-PR4424?expand=1

This is happening for me on WHMCS 7.8 and PHP 7.3.

**Comment by hluaces** [comment]
Still persists on 1.1.20.

**Comment by hluaces** [comment]
Still persists on 1.1.24
